// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxBe7ykfxFQEQ-m5QMGGyXpe84ivlRWAE',
    appId: '1:164096463367:web:0ac679e16b823ed3c590a2',
    messagingSenderId: '164096463367',
    projectId: 'loanmobileapp',
    authDomain: 'loanmobileapp.firebaseapp.com',
    storageBucket: 'loanmobileapp.appspot.com',
    measurementId: 'G-4K9THXTT9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapFAdsWiDwPefL-VrsGy76kDK22WbaDo',
    appId: '1:164096463367:android:dcabb56f8e5408b5c590a2',
    messagingSenderId: '164096463367',
    projectId: 'loanmobileapp',
    storageBucket: 'loanmobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqFoilRDHWxnNVyVYinmXiX7UDB4rpQM',
    appId: '1:164096463367:ios:389a65ae0cbb6d0dc590a2',
    messagingSenderId: '164096463367',
    projectId: 'loanmobileapp',
    storageBucket: 'loanmobileapp.appspot.com',
    iosBundleId: 'com.example.loanmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqFoilRDHWxnNVyVYinmXiX7UDB4rpQM',
    appId: '1:164096463367:ios:389a65ae0cbb6d0dc590a2',
    messagingSenderId: '164096463367',
    projectId: 'loanmobileapp',
    storageBucket: 'loanmobileapp.appspot.com',
    iosBundleId: 'com.example.loanmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxBe7ykfxFQEQ-m5QMGGyXpe84ivlRWAE',
    appId: '1:164096463367:web:1c499b106299b85fc590a2',
    messagingSenderId: '164096463367',
    projectId: 'loanmobileapp',
    authDomain: 'loanmobileapp.firebaseapp.com',
    storageBucket: 'loanmobileapp.appspot.com',
    measurementId: 'G-CCVHZVC8TG',
  );
}
